apiVersion: v1
kind: Service
metadata:
  name: keeptorch-service
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app: keeptorch
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080