name: RollbackMigration
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "environment"
        options:
          - "load-testing"
          - "staging"
          - "prod"
        required: true
jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
    - name: Hi
      run: echo "hello, world ${{ github.event.inputs.env }}"